import type { ApprovalChoice, PendingApproval } from "../shared/types.js";

interface PendingEntry {
  approval: PendingApproval;
  resolve(choice: ApprovalChoice): void;
}

const VALID_CHOICES: ApprovalChoice[] = ["allow-once", "always-allow", "deny"];

function isValidChoice(choice: unknown): choice is ApprovalChoice {
  return VALID_CHOICES.includes(choice as ApprovalChoice);
}

export class ApprovalQueue {
  private pending = new Map<string, PendingEntry>();
  private listener: ((approval: PendingApproval) => void) | null = null;

  onRequest(cb: (approval: PendingApproval) => void): void {
    this.listener = cb;
  }

  request(approval: PendingApproval): Promise<ApprovalChoice> {
    if (this.pending.has(approval.id)) {
      // The id is generated by the caller for correlation purposes and must
      // be unique. Silently overwriting an existing entry would leak the
      // original promise's resolve() and hang that caller forever.
      throw new Error(`ApprovalQueue.request: duplicate pending approval id "${approval.id}"`);
    }
    return new Promise<ApprovalChoice>((resolve) => {
      this.pending.set(approval.id, { approval, resolve });
      this.listener?.(approval);
    });
  }

  respond(id: string, choice: ApprovalChoice): void {
    // Defense in depth: a compromised renderer could call the IPC handler
    // directly (bypassing the typed preload wrapper) with an arbitrary
    // value. Never let a malformed choice reach the awaiting caller as if
    // it were a real decision — ignore it instead of resolving with
    // garbage that downstream code might treat as an allow.
    if (!isValidChoice(choice)) {
      return;
    }
    const entry = this.pending.get(id);
    if (!entry) {
      return;
    }
    this.pending.delete(id);
    entry.resolve(choice);
  }

  denyAll(): void {
    for (const entry of this.pending.values()) {
      entry.resolve("deny");
    }
    this.pending.clear();
  }

  pendingCount(): number {
    return this.pending.size;
  }
}
